# Standards: 0.1
---
- name: Fact gimp user
  set_fact:
    gimp_user: "{{ gimp_user | default(homebrew_user) | default(ansible_user_id) }}"
  tags:
    - gimp

- become: "{{ (gimp_user != ansible_user_id) | bool }}"
  become_user: "{{ gimp_user }}"
  block:
    - name: Install required package
      ignore_errors: True
      homebrew_cask:
        name: gimp
        greedy: True
        options: appdir=/Applications
        accept_external_apps: False
        state: upgraded
      tags:
        - gimp

    - name: Remove quarantine flag
      register: gimp_quarantine
      failed_when: gimp_quarantine.rc != 0 and "No such xattr" not in gimp_quarantine.stderr
      changed_when: gimp_quarantine.rc == 0
      command: xattr -d com.apple.quarantine /Applications/GIMP-2.10.app
      tags:
        - gimp

    - name: Install pidof package
      homebrew:
        name: pidof
      tags:
        - gimp

    - name: Check program running
      register: gimp_running
      check_mode: False
      failed_when: False
      changed_when: gimp_running.stdout | length > 0 | bool
      command: pidof GIMP-2.10
      tags:
        - gimp

    - name: Fact program running
      set_fact:
        gimp_started: "{{ gimp_running.stdout_lines | length > 0 | bool }}"
      tags:
        - gimp

...
